# Generated by Django 4.2.9 on 2024-02-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0243_event_picture'),
        ('pretixbase', '0254_alter_logentry_organizer_link_and_more'),
    ]

    operations = [
    ]
