# Generated by Django 4.2.9 on 2024-02-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0256_alter_reusablemedium_index_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reusablemedium',
            index=models.Index(fields=['identifier', 'type', 'organizer'], name='pretixbase__identif_798d22_idx'),
        ),
    ]
