# Generated by Django 4.2.9 on 2024-02-08 19:25

from django.db import migrations
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0257_reusablemedium_pretixbase__identif_798d22_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subtitle',
            field=i18nfield.fields.I18nCharField(max_length=200, null=True),
        ),
    ]
