# Generated by Django 4.2.20 on 2025-03-11 15:00

from django.db import migrations, models
import i18nfield.fields
import pretix.base.models.event


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0277_customerssoclient_require_pkce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='desc',
            field=i18nfield.fields.I18nTextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.ImageField(max_length=255, null=True, upload_to=pretix.base.models.event.eventpicture_upload_to),
        ),
        migrations.AddField(
            model_name='event',
            name='subtitle',
            field=i18nfield.fields.I18nCharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='locale',
            field=models.CharField(default='en', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(default='en', max_length=50),
        ),
    ]
